### ISSUE TITLE
Unsubscribe redux store (and some comments)

### ISSUE THREAD

**Issue by smalluban** [drejohnson/hybrids-pwa#1]
I must say, I am very impressed :) Hybrids are public for less than two months, and here we have the first project using the library. 

**About your views.** The main concept of the library is to export the raw structure of the element, and define it when it is needed. I understand, that your concept is to load them dynamically, so you define them in the file where they are defined. However, even with this pattern, I think it is better to export definition like this:

```javascript
const HomeView = {...};
define('home-view', HomeView);
export default HomeView;
```

or if you want to export element constructor (as you do now):

```javascript
export const HomeView = {...};
export default define('home-view', HomeView);
```

Exporting definition allows using properties in other elements, or use it as a reference for DOM traversing (with `children` or `parent` factories).

**Redux store**.
https://github.com/drejohnson/hybrids-pwa/blob/f22ccb5e8b2773f90e9a2db03965416072d50f37/src/connect.js#L10

I think you forgot `return` statement here. For this reason store is not unsubscribing disconnected elements. In my example it worked because that method was one line arrow function (with built-in renturn statement).

**Comment by drejohnson** [comment]
Thanks for the feedback. I made the changes you suggested.
